apiVersion: v1
kind: Service
metadata:
  name: {{Name}}
  namespace: {{SpaceName}}
spec:
  ports:
  - port: {{PodPort}}
    targetPort: {{ContainerPort}}
  selector:
    {{ContainerKey}}: {{ContainerValue}}
  clusterIP: None
  #type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{Name}}
  namespace: {{SpaceName}}
spec:
  selector:
    matchLabels:
      {{ContainerKey}}: {{ContainerValue}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{ContainerKey}}: {{ContainerValue}}
    spec:
      nodeSelector:
        node: node1
      containers:
      - image: {{Image}}
        name: {{ImageName}}
        ports:
        - containerPort: {{ContainerPort}}
          name: {{ContainerPortName}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{Name}}
  namespace: {{SpaceName}}
spec:
  rules:
  - host: {{Name}}.mooc.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{Name}}
          servicePort: {{PodPort}}